CREATE TABLE [dbo].[BusinessItem]
(
	[Id]							UNIQUEIDENTIFIER	NOT NULL, 
    [Name]							NVARCHAR(300)		NULL, 
	[ShortDescription]				NVARCHAR(max)		NULL, 
	[FullDescription]				NVARCHAR(max)		NULL, 
    [Code]							NVARCHAR(300)		NULL,
	[EcommercePublished]			bit NULL, 
	[EcommerceShowOnHomePage]		bit NULL, 
	[CanBuy]						bit NOT NULL DEFAULT 0, 
	[CanSell]						bit NOT NULL DEFAULT 0, 
	[CanManufacture]				bit NOT NULL DEFAULT 0, 
	[CanConsume]					bit NOT NULL DEFAULT 0, 
	--[RequiredStock]					BIT	NOT NULL DEFAULT 0,
	--[Manufactured]					BIT					NOT NULL DEFAULT 0,
    [BusinessItem_Category_Id]		UNIQUEIDENTIFIER	NOT NULL, 
	[BusinessItem_Type_Id]			UNIQUEIDENTIFIER	NOT NULL, 
	--[UnitOfMeasure_Id]				UNIQUEIDENTIFIER	NULL,
	[BusinessItem_Class_Id]			UNIQUEIDENTIFIER	NOT NULL,
	--[WarehouseStorage_Id]			UNIQUEIDENTIFIER	NULL,
	[Warranty]						NVARCHAR(max)		NULL, 
	[RowStatus]						int                 not null,
	[Locked]						BIT					NOT NULL DEFAULT 0,
	[Required]						BIT					NOT NULL DEFAULT 0,
	[Employee_Id]					uniqueidentifier	null,
	[CreatedBy]						uniqueidentifier	null,
	[CreatedDate]					datetime      null,
	[ModifiedBy]					uniqueidentifier     null,
	[ModifiedDate]					datetime             null, 
    [Picture] NVARCHAR(MAX) NULL, 
    CONSTRAINT [PK_BusinessItem] PRIMARY KEY ([Id]), 
    CONSTRAINT [FK_BusinessItem_Category] FOREIGN KEY ([BusinessItem_Category_Id]) REFERENCES [BusinessItem_Category]([Id]), 
    CONSTRAINT [FK_BusinessItem_Type] FOREIGN KEY ([BusinessItem_Type_Id]) REFERENCES [BusinessItem_Type]([Id]), 
    --CONSTRAINT [FK_BusinessItem_UnitOfMeasure] FOREIGN KEY ([UnitOfMeasure_Id]) REFERENCES [UnitOfMeasure]([Id]), 
    CONSTRAINT [FK_BusinessItem_Class] FOREIGN KEY ([BusinessItem_Class_Id]) REFERENCES [BusinessItem_Class]([Id]), 
    --CONSTRAINT [FK_BusinessItem_Warehouse] FOREIGN KEY ([WarehouseStorage_Id]) REFERENCES [WarehouseStorage]([Id])
)
