CREATE TABLE [dbo].[PurchaseInvoice]
(
	[Id]								UNIQUEIDENTIFIER	NOT NULL, 
	[Batch]								NVARCHAR(100)		NULL,
	[Date]								DATE				NOT NULL, 
	[TotalAmountWithoutTaxes]			DECIMAL(18, 5)		NOT NULL DEFAULT 0, 
	[DiscountAmount]					DECIMAL(18, 5)		NOT NULL DEFAULT 0, 
	[TaxAmount]							DECIMAL(18, 5)		NOT NULL DEFAULT 0, 
	[TipAmount]							DECIMAL(18, 5)		NOT NULL DEFAULT 0, 
	[TotalAmount]						DECIMAL(18, 5)		NOT NULL DEFAULT 0, 
	[CurrencyCode]						NVARCHAR(MAX)		NULL, 
	[CurrencyName]						NVARCHAR(MAX)		NULL, 
	--Supplier
	[SupplierName]						NVARCHAR(MAX)		NULL, 
	[SupplierLegalIdTypeCode]			NVARCHAR(MAX)		NULL, 
	[SupplierLegalId]					NVARCHAR(MAX)		NULL, 
	[SupplierAddress]					NVARCHAR(MAX)		NULL,
	--[SupplierShippingAddress]			NVARCHAR(MAX)		NULL,
	[SupplierPhone]						NVARCHAR(MAX)		NULL,
	[SupplierEmail]						NVARCHAR(MAX)		NULL,
	--Document
	[Number]							NVARCHAR(MAX)		NULL,
	[DocumentNumber]					NVARCHAR(MAX)		NULL,
	--Company
	--[CompanyLegalId]					NVARCHAR(MAX)		NULL, 
	--[CompanyName1]						NVARCHAR(MAX)		NULL, 
	--[CompanyName2]						NVARCHAR(MAX)		NULL, 
	--[CompanyTaxPayerId]					NVARCHAR(MAX)		NULL, 
	--[CompanyAddress]					NVARCHAR(MAX)		NULL, 
	--[CompanyPhone]						NVARCHAR(MAX)		NULL, 
	--[CompanyAccountingRequired]			NVARCHAR(100)		NULL, 
	----Company_Place
	--[CompanyPlaceCode]					NVARCHAR(MAX)		NULL, 
	--[CompanyPlaceAddress]				NVARCHAR(MAX)		NULL, 
	--[CompanyPlacePhone]					NVARCHAR(MAX)		NULL, 
	--[CompanyPointOfSaleCode]			NVARCHAR(MAX)		NULL, 
	--Contract
	--[ContractNumber]					BIGINT				NULL, 
	--[ContractPhysicalNumber]			NVARCHAR(MAX)		NULL, 
	--Informative fields
	[Informative1]						NVARCHAR(MAX)		NULL, 
	[Informative2]						NVARCHAR(MAX)		NULL, 
	[Informative3]						NVARCHAR(MAX)		NULL, 
	[Informative4]						NVARCHAR(MAX)		NULL, 
	[Informative5]						NVARCHAR(MAX)		NULL, 
	[Informative6]						NVARCHAR(MAX)		NULL, 
	[Informative7]						NVARCHAR(MAX)		NULL, 
	[Informative8]						NVARCHAR(MAX)		NULL, 
	[Informative9]						NVARCHAR(MAX)		NULL, 
	[Informative10]						NVARCHAR(MAX)		NULL, 
	[Informative11]						NVARCHAR(MAX)		NULL, 
	[Informative12]						NVARCHAR(MAX)		NULL, 
	[Informative13]						NVARCHAR(MAX)		NULL, 
	[Informative14]						NVARCHAR(MAX)		NULL, 
	[Informative15]						NVARCHAR(MAX)		NULL, 
	[Purchase_Id]						UNIQUEIDENTIFIER	NOT NULL, 
	--[Company_PointOfSale_Id]			UNIQUEIDENTIFIER	NOT NULL,
	[RowStatus]							INT					NOT NULL,
	[Locked]							BIT					NOT NULL DEFAULT 0,
	[Required]							BIT					NOT NULL DEFAULT 0,
	[Employee_Id]						UNIQUEIDENTIFIER	NULL,
	[CreatedBy]							UNIQUEIDENTIFIER	NULL,
	[CreatedDate]						DATETIME			NULL,
	[ModifiedBy]						UNIQUEIDENTIFIER	NULL,
	[ModifiedDate]						DATETIME			NULL,
    [Picture] NVARCHAR(MAX) NULL, 
    CONSTRAINT [PK_PurchaseInvoice] PRIMARY KEY ([Id]), 
    CONSTRAINT [FK_PurchaseInvoice_Purchase] FOREIGN KEY ([Purchase_Id]) REFERENCES [Purchase]([Id]), 
)
