--Venciemientos
CREATE TABLE [dbo].[InvestmentFund_Maturity]
(
		[Id]						UNIQUEIDENTIFIER NOT NULL,
		[Portafolio]				NVARCHAR(100) NULL, 
   		[TivId]						NVARCHAR(100) NULL,
		[Codigo]					NVARCHAR(100) NULL, 
		[Emisor]					NVARCHAR(1000) NULL, 
		[Sector]					NVARCHAR(100) NULL, 
		[TipoRenta]					NVARCHAR(100) NULL, 
		[TipoValor]					NVARCHAR(100) NULL, 
		[Subtipo]					NVARCHAR(100) NULL, 
		[TipoTasa]					NVARCHAR(100) NULL,
		[TituloTasaInteres]			DECIMAL(18,10) NULL,
		[TituloPrecioSpot]			DECIMAL(18,10) NULL,
		[ValorEfectivo]				DECIMAL(18,10) NULL,
		[ValorNominalTotal]			DECIMAL(18,10) NULL,
		[ValorNominalUnitario]		DECIMAL(18,10) NULL,
		[TituloCodigo]				NVARCHAR(100) NULL, 
		[TituloRendimiento]			DECIMAL(18,10) NULL,
		[InteresAcumulado]			DECIMAL(18,10) NULL,
		[TituloTasaMargen]			DECIMAL(18,10) NULL,
		[TituloTasaCuponRemanente]	DECIMAL(18,10) NULL,
		[MonedaNombre]				NVARCHAR(100) NULL, 
		[MonedaCodigo]				NVARCHAR(100) NULL, 
		[Plazo]						NVARCHAR(100) NULL, 
		[Cupon]						BIT NULL, 
		[TipoCategoria]				NVARCHAR(100) NULL,
		[FechaVencimiento]			DATETIME2 NULL, 
		[FechaEmision]				DATETIME2 NULL,
		[FechaCorte]				DATETIME2 NULL, 
		[Numeracion]				NVARCHAR(100) NULL, 
		[DesmaterializadoNombre]	NVARCHAR(100) NULL,
		[DiasTranscurridos]			INT NULL,
		[FechaCompra]				DATETIME2 NULL, 
		[PlazoTotal]				INT NULL,
		[PlazoVencer]				INT NULL,
		[FechaCapital]				DATETIME2 NULL,
		[FechaInteres]				DATETIME2 NULL,
		[DiasAcrual]				INT NULL, 
		[FechaAcrual]				DATETIME2 NULL, 
		[Cantidad]					DECIMAL(18,10) NULL,
		[Valor]						NVARCHAR(100) NULL,
		[Calificadora]				NVARCHAR(100) NULL,
		[TipoBase]					NVARCHAR(100) NULL,
		[Custodio]					NVARCHAR(100) NULL,
		[RendimientoOperacion]		DECIMAL(18,10) NULL, 
		[FechaCalificacion]			DATETIME2 NULL,
		[SiglasTipoValor]			NVARCHAR(100) NULL, 
		[GrupoTipoValor]			NVARCHAR(100) NULL,
		[ValorEfectivoCompra]		DECIMAL(18,10) NULL, 
		[PrecioCompra]				DECIMAL(18,10),
		[FechaVencimientoCupon]		DATETIME2 NULL,
		[FechaVencimientoCapital]	DECIMAL(18,10) NULL,
		[VencimientoInteres]		DECIMAL(18,10) NULL,
		[TasaCupon]					DECIMAL(18,10) NULL,
		[CodigoEmisor]				NVARCHAR(100) NULL, 
		[Retencion]					NVARCHAR(100) NULL,
		[FechaVencimientoInteres]	DECIMAL(18,10) NULL,
		[NumeroDeCuenta]			NVARCHAR(100) NULL,
		[Banco]						NVARCHAR(100) NULL,
		[Observaciones]				NVARCHAR(100) NULL,
		[Total]						DECIMAL(18,10) NULL,

		[LoadDate] DATETIME2 NOT NULL, 
    CONSTRAINT [PK_BVQ_Maturities] PRIMARY KEY ([Id]) 
	)
