CREATE TABLE [dbo].[FixedAsset]
(
	[Id]							UNIQUEIDENTIFIER	NOT NULL, 
	[BusinessItemVariation_Name]	NVARCHAR(150)		NULL,
	[AdmissionDate]					DATETIME			NOT NULL,
	[BusinessItemVariation_Id]		UNIQUEIDENTIFIER	NOT NULL,
	[Cost]							DECIMAL(18, 5)		NULL,
	[SalePrice]						DECIMAL(18, 5)		NULL,
	[FixedAssetIncome_Id]			UNIQUEIDENTIFIER	NOT NULL, 
	[FixedAssetOutput_Id]			UNIQUEIDENTIFIER	NULL, 
	[Company_Place_Id]				UNIQUEIDENTIFIER	NOT NULL, 
    [SaleInvoice_Id]				UNIQUEIDENTIFIER	NULL, 
	[Serial]						NVARCHAR(200)		NULL, 
	[Location]						NVARCHAR(300)		NULL, 
	[ExpirationDate]				DATETIME			NULL,
	[FixedAsset_Status_Id]			UNIQUEIDENTIFIER	NOT NULL, 
	[RowStatus]						int                 not null,
	[Locked]						BIT					NOT NULL DEFAULT 0,
	[Required]						BIT					NOT NULL DEFAULT 0,
	[Employee_Id]					uniqueidentifier	null,
	[CreatedBy]						uniqueidentifier	null,
	[CreatedDate]					datetime			null,
	[ModifiedBy]					uniqueidentifier	null,
	[ModifiedDate]					datetime			null, 
    [Picture] NVARCHAR(MAX) NULL, 
    CONSTRAINT [PK_FixedAsset] PRIMARY KEY ([Id]), 
    CONSTRAINT [FK_FixedAsset_BusinessItemVariation] FOREIGN KEY ([BusinessItemVariation_Id]) REFERENCES [BusinessItemVariation]([Id]), 
    CONSTRAINT [FK_FixedAsset_FixedAssetIncome] FOREIGN KEY ([FixedAssetIncome_Id]) REFERENCES [FixedAssetIncome]([Id]), 
    CONSTRAINT [FK_FixedAsset_FixedAssetOutput] FOREIGN KEY ([FixedAssetOutput_Id]) REFERENCES [FixedAssetOutput]([Id]), 
    CONSTRAINT [FK_FixedAsset_FixedAssetStatus] FOREIGN KEY ([FixedAsset_Status_Id]) REFERENCES [FixedAsset_Status]([Id]), 
    CONSTRAINT [FK_FixedAsset_SaleInvoice] FOREIGN KEY ([SaleInvoice_Id]) REFERENCES [SaleInvoice]([Id]), 
    CONSTRAINT [FK_FixedAsset_Company_Palce] FOREIGN KEY ([Company_Place_Id]) REFERENCES [Company_Place]([Id]), 
	--CONSTRAINT [FK_BusinessItem_UnitOfMeasure] FOREIGN KEY ([UnitOfMeasure_Id]) REFERENCES [UnitOfMeasure]([Id])
)
