CREATE TABLE [dbo].[Email]
(
	[Id]								UNIQUEIDENTIFIER	NOT NULL, 
	[ResponsableEmployee_Id]			UNIQUEIDENTIFIER	NOT NULL,
	[Customer_Id]						UNIQUEIDENTIFIER	NOT NULL,
	[Customer_Contact_Id]				UNIQUEIDENTIFIER	NULL,
	[SenderEmailAddress]				NVARCHAR(300)		NULL, 
	[SenderName]						NVARCHAR(300)		NULL, 
	[Receiver]							NVARCHAR(300)		NULL, 
	[ReceiverEmailAddress]				NVARCHAR(300)		NULL, 
	[Subject]							NVARCHAR(300)		NULL, 
    [Body]								NVARCHAR(MAX)		NULL, 
	[MassiveEmail_Id]					UNIQUEIDENTIFIER	NULL,
	[Email_State_Id]					UNIQUEIDENTIFIER	NOT NULL,
	[SendDate]							DATETIME			NULL,
	[Comment]							NVARCHAR(300)		NULL, 
	[Received]							DATETIME			NULL, 
	[Read]								DATETIME			NULL, 
	[Opened]							DATETIME			NULL, 
	[Rejected]							DATETIME			NULL, 
	[RowStatus]							INT					NOT NULL,
	[Locked]							BIT					NOT NULL DEFAULT 0,
	[Required]							BIT					NOT NULL DEFAULT 0,
	[Employee_Id]						UNIQUEIDENTIFIER	NULL,
	[CreatedBy]							UNIQUEIDENTIFIER	NULL,
	[CreatedDate]						DATETIME			NULL,
	[ModifiedBy]						UNIQUEIDENTIFIER	NULL,
	[ModifiedDate]						DATETIME			NULL,
    [Picture] NVARCHAR(MAX) NULL, 
    CONSTRAINT [PK_Email] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_Email_Customer] FOREIGN KEY ([Customer_Id]) REFERENCES [Customer]([Id]),
    CONSTRAINT [FK_Email_CustomerContact] FOREIGN KEY ([Customer_Contact_Id]) REFERENCES [Customer_Contact]([Id]),
    CONSTRAINT [FK_Email_MassiveEmail] FOREIGN KEY ([MassiveEmail_Id]) REFERENCES [MassiveEmail]([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_Email_Email_State] FOREIGN KEY ([Email_State_Id]) REFERENCES [Email_State]([Id])

)
