CREATE TABLE [dbo].[EmailTemplate]
(
	[Id]								UNIQUEIDENTIFIER	NOT NULL, 
    [Name]								NVARCHAR(100)		NOT NULL, 
    [Description]						NVARCHAR(500)		NULL, 
    [To]								NVARCHAR(MAX)		NOT NULL, 
    [Subject]							NVARCHAR(MAX)		NOT NULL, 
    [Body]								NVARCHAR(MAX)		NOT NULL, 
    [Entity_Id]							UNIQUEIDENTIFIER	NULL,
	[RowStatus]							INT					NOT NULL,
	[Locked]							BIT					NOT NULL DEFAULT 0,
	[Required]							BIT					NOT NULL DEFAULT 0,
	[Employee_Id]						UNIQUEIDENTIFIER	NULL,
	[CreatedBy]							UNIQUEIDENTIFIER	NULL,
	[CreatedDate]						DATETIME			NULL,
	[ModifiedBy]						UNIQUEIDENTIFIER	NULL,
	[ModifiedDate]						DATETIME			NULL,
    [Picture] NVARCHAR(MAX) NULL, 
    CONSTRAINT [PK_EmailTemplate] PRIMARY KEY ([Id]),  
)
