CREATE TABLE [dbo].[Project_StoryboardTask]
(
	[Id]								UNIQUEIDENTIFIER	NOT NULL, 
    [Name]								VARCHAR(500)		NOT NULL, 
	[Minutes]							INT					NULL,
	[IsBillable]						BIT					NULL, 
	[BilliableMinutes]					INT					NULL,
	[Project_Storyboard_Id]				UNIQUEIDENTIFIER	NOT NULL,
	[RowStatus]							INT					NOT NULL,
	[Locked]							BIT					NOT NULL DEFAULT 0,
	[Required]							BIT					NOT NULL DEFAULT 0,
	[Employee_Id]						UNIQUEIDENTIFIER	NULL,
	[CreatedBy]							UNIQUEIDENTIFIER	NULL,
	[CreatedDate]						DATETIME			NULL,
	[ModifiedBy]						UNIQUEIDENTIFIER	NULL,
	[ModifiedDate]						DATETIME			NULL,
    [Picture] NVARCHAR(MAX) NULL, 
    CONSTRAINT [FK_Project_StoryboardTask] FOREIGN KEY ([Project_Storyboard_Id]) REFERENCES [Project_Storyboard]([Id]), 
    CONSTRAINT [PK_Project_StoryboardTask] PRIMARY KEY ([Id]), 
)
