CREATE TABLE [dbo].[Employee]
(
	[Id]								UNIQUEIDENTIFIER	NOT NULL, 
	[Name]								NVARCHAR(300)		NULL, 
	[Phone]								NVARCHAR(100)		NULL, 
	[Birth]								DATETIME			NULL, 
	[Email]								NVARCHAR(200)		NULL, 
	[Password]							NVARCHAR(200)		NULL, 
	[Appointment]						NVARCHAR(200)		NULL, 
	[Company_Place_Id]					UNIQUEIDENTIFIER	NULL,
	[Company_EmissionPoint_Id]			UNIQUEIDENTIFIER	 null,
	[Role_Id]							UNIQUEIDENTIFIER	 null,
	[RowStatus]							INT					NOT NULL,
	[Locked]							BIT					NOT NULL DEFAULT 0,
	[Required]							BIT					NOT NULL DEFAULT 0,
	[Employee_Id]						UNIQUEIDENTIFIER	NULL,
	[CreatedBy]							UNIQUEIDENTIFIER	NULL,
	[CreatedDate]						DATETIME			NULL,
	[ModifiedBy]						UNIQUEIDENTIFIER	NULL,
	[ModifiedDate]						DATETIME			NULL,
    [Picture] NVARCHAR(MAX) NULL, 
    CONSTRAINT [PK_Employee] PRIMARY KEY ([Id]),
	CONSTRAINT [FK_Employe_Role] FOREIGN KEY ([Role_Id]) REFERENCES [Role]([Id]),
	CONSTRAINT [FK_Employe_CompanyPlace] FOREIGN KEY ([Company_Place_Id]) REFERENCES [Company_Place]([Id]),
	CONSTRAINT [FK_Employe_CompanyPointOfSale] FOREIGN KEY ([Company_EmissionPoint_Id]) REFERENCES [Company_EmissionPoint]([Id])
)
