CREATE TABLE [dbo].[SaleInvoicePayment]
(
	[Id]								UNIQUEIDENTIFIER	NOT NULL, 
    [Date]								DATETIME			NOT NULL, 
	[OwnerLegalId]						NVARCHAR(MAX)		NULL,
	[OwnerName]							NVARCHAR(MAX)		NULL,
	[ExpirationDate]					DATE				NULL,
	[BankCode]							NVARCHAR(MAX)		NULL,
	[BankName]							NVARCHAR(MAX)		NULL,
	[Number]							NVARCHAR(MAX)		NULL,
	[CustomerLegalId]					NVARCHAR(MAX)		NULL,
	[CustomerName]						NVARCHAR(MAX)		NULL,
	[AutomaticDebit]					BIT					NOT NULL, 
	[Amount]							DECIMAL(18, 5)		NOT NULL, 
	[Confirmed]							BIT					NOT NULL,
	[Comment]							NVARCHAR(MAX)		NULL,
	[SaleInvoice_Id]					UNIQUEIDENTIFIER	NOT NULL,
	[Customer_PaymentOption_Id]			UNIQUEIDENTIFIER	NULL,
	[RowStatus]							INT					NOT NULL,
	[Locked]							BIT					NOT NULL DEFAULT 0,
	[Required]							BIT					NOT NULL DEFAULT 0,
	[Employee_Id]						UNIQUEIDENTIFIER	NULL,
	[CreatedBy]							UNIQUEIDENTIFIER	NULL,
	[CreatedDate]						DATETIME			NULL,
	[ModifiedBy]						UNIQUEIDENTIFIER	NULL,
	[ModifiedDate]						DATETIME			NULL,
    [Picture] NVARCHAR(MAX) NULL, 
    CONSTRAINT [PK_SaleInvoicePayment] PRIMARY KEY ([Id]), 
    CONSTRAINT [FK_SaleInvoicePayment_SaleInvoice] FOREIGN KEY ([SaleInvoice_Id]) REFERENCES [SaleInvoice]([Id]) ON DELETE CASCADE, 
    CONSTRAINT [FK_SaleInvoicePayment_CustomerPaymentOption] FOREIGN KEY ([Customer_PaymentOption_Id]) REFERENCES [Customer_PaymentOption]([Id]) 
)
