CREATE TABLE [dbo].[Service]
(
	[Id]								UNIQUEIDENTIFIER	NOT NULL, 
	[Number]							BIGINT				NULL,
	[Service_Type_Id]					UNIQUEIDENTIFIER	NOT NULL,
	[RequestDate]						DATETIME			NULL,
	[ResolutionDate]					DATETIME			NULL,
    [Problem]							NVARCHAR(2000)		NULL, 
    [Resolution]						NVARCHAR(2000)		NULL, 
	[Service_Status_Id]					UNIQUEIDENTIFIER	NOT NULL,
	[Contract_Id]						UNIQUEIDENTIFIER	NULL,
	[Service_Priority_Id]				UNIQUEIDENTIFIER	NOT NULL,
	[Customer_Id]						UNIQUEIDENTIFIER	NOT NULL,
	[Contact_Id]						UNIQUEIDENTIFIER	NULL,
	[SaleInvoice_Line_Id]				UNIQUEIDENTIFIER	NULL, 
	[RowStatus]							INT					NOT NULL,
	[Locked]							BIT					NOT NULL DEFAULT 0,
	[Required]							BIT					NOT NULL DEFAULT 0,
	[Employee_Id]						UNIQUEIDENTIFIER	NULL,
	[CreatedBy]							UNIQUEIDENTIFIER	NULL,
	[CreatedDate]						DATETIME			NULL,
	[ModifiedBy]						UNIQUEIDENTIFIER	NULL,
	[ModifiedDate]						DATETIME			NULL,
    [Picture] NVARCHAR(MAX) NULL, 
    CONSTRAINT [PK_Service] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_Service_Service_Type] FOREIGN KEY ([Service_Type_Id]) REFERENCES [Service_Type]([Id]), 
    CONSTRAINT [FK_Service_Status] FOREIGN KEY ([Service_Status_Id]) REFERENCES [Service_Status]([Id]), 
    CONSTRAINT [FK_Service_Priority] FOREIGN KEY ([Service_Priority_Id]) REFERENCES [Service_Priority]([Id]), 
    CONSTRAINT [FK_Service_Customer] FOREIGN KEY ([Customer_Id]) REFERENCES [Customer]([Id]), 
    CONSTRAINT [FK_Service_Contact] FOREIGN KEY ([Contact_Id]) REFERENCES [Contact]([Id]), 
    CONSTRAINT [FK_Service_Contract] FOREIGN KEY ([Contract_Id]) REFERENCES [Contract]([Id]),
    CONSTRAINT [FK_Service_SaleInvoice_Line] FOREIGN KEY ([SaleInvoice_Line_Id]) REFERENCES [SaleInvoice_Line]([Id]),
    CONSTRAINT [FK_Service_Employee] FOREIGN KEY ([Employee_Id]) REFERENCES [Employee]([Id]) 

)
