CREATE TABLE [dbo].[Contract]
(
	[Id]								UNIQUEIDENTIFIER	NOT NULL, 
    [Number]							BIGINT				NULL, 
	[PhysicalNumber]					NVARCHAR(100)		NULL, 
	[SignCustomerName]					NVARCHAR(500)		NULL,
	[SignCompanyName]					NVARCHAR(500)		NULL,
	[SigningDate]						DATE				NULL, 
	[ValidityStart]						DATE				NULL, 
	[ValidityEnd]						DATE				NULL, 
	[RealEnd]							DATE				NULL, 
	[Contract_EndReason_Id]				UNIQUEIDENTIFIER	NULL,
	[Contract_Status_Id]				UNIQUEIDENTIFIER	NULL, 
	[Contract_Type_Id]					UNIQUEIDENTIFIER	NOT NULL, 
	[Sale_Id]							UNIQUEIDENTIFIER	NULL, 
	[RowStatus]							INT					NOT NULL,
	[Locked]							BIT					NOT NULL DEFAULT 0,
	[Required]							BIT					NOT NULL DEFAULT 0,
	[Employee_Id]						UNIQUEIDENTIFIER	NULL,
	[CreatedBy]							UNIQUEIDENTIFIER	NULL,
	[CreatedDate]						DATETIME			NULL,
	[ModifiedBy]						UNIQUEIDENTIFIER	NULL,
	[ModifiedDate]						DATETIME			NULL,
    [Picture] NVARCHAR(MAX) NULL, 
    CONSTRAINT [PK_Contract] PRIMARY KEY ([Id]), 
    CONSTRAINT [FK_Contract_Type] FOREIGN KEY ([Contract_Type_Id]) REFERENCES [Contract_Type]([Id]),
    CONSTRAINT [FK_Contract_Sale] FOREIGN KEY ([Sale_Id]) REFERENCES [Sale]([Id]), 
    CONSTRAINT [FK_Contract_Status] FOREIGN KEY ([Contract_Status_Id]) REFERENCES [Contract_Status]([Id]), 
    CONSTRAINT [FK_Contract_EndReason] FOREIGN KEY ([Contract_EndReason_Id]) REFERENCES [Contract_EndReason]([Id]), 
)
