CREATE TABLE [dbo].[Inventory]
(
	[Id]							UNIQUEIDENTIFIER	NOT NULL, 
	[BusinessItemVariation_Name]	NVARCHAR(150)		NULL,
	[AdmissionDate]					DATETIME			NOT NULL,
	[BusinessItemVariation_Id]		UNIQUEIDENTIFIER	NOT NULL,
	[Cost]							DECIMAL(18, 5)		NULL,
	[SalePrice]						DECIMAL(18, 5)		NULL,
	[InventoryIncome_Id]			UNIQUEIDENTIFIER	NOT NULL, 
	[InventoryOutput_Id]			UNIQUEIDENTIFIER	NULL, 
	[Warehouse_Id]					UNIQUEIDENTIFIER	NOT NULL, 
    [Manufacture_Id]				UNIQUEIDENTIFIER	NULL, 
    [SaleInvoice_Id]				UNIQUEIDENTIFIER	NULL, 
	[Serial]						NVARCHAR(200)		NULL, 
	[Location]						NVARCHAR(300)		NULL, 
	[ExpirationDate]				DATETIME			NULL,
	[Inventory_Status_Id]			UNIQUEIDENTIFIER	NOT NULL, 
	[RowStatus]						int                 not null,
	[Locked]						BIT					NOT NULL DEFAULT 0,
	[Required]						BIT					NOT NULL DEFAULT 0,
	[Employee_Id]					uniqueidentifier	null,
	[CreatedBy]						uniqueidentifier	null,
	[CreatedDate]					datetime			null,
	[ModifiedBy]					uniqueidentifier	null,
	[ModifiedDate]					datetime			null, 
    [Picture] NVARCHAR(MAX) NULL, 
    CONSTRAINT [PK_Inventory] PRIMARY KEY ([Id]), 
    CONSTRAINT [FK_Inventory_BusinessItemVariation] FOREIGN KEY ([BusinessItemVariation_Id]) REFERENCES [BusinessItemVariation]([Id]), 
    CONSTRAINT [FK_Inventory_InventoryIncome] FOREIGN KEY ([InventoryIncome_Id]) REFERENCES [InventoryIncome]([Id]), 
    CONSTRAINT [FK_Inventory_InventoryOutput] FOREIGN KEY ([InventoryOutput_Id]) REFERENCES [InventoryOutput]([Id]), 
    CONSTRAINT [FK_Inventory_InventoryStatus] FOREIGN KEY ([Inventory_Status_Id]) REFERENCES [Inventory_Status]([Id]), 
    CONSTRAINT [FK_Inventory_Manufacturee] FOREIGN KEY ([Manufacture_Id]) REFERENCES [Manufacture]([Id]), 
    CONSTRAINT [FK_Inventory_SaleInvoice] FOREIGN KEY ([SaleInvoice_Id]) REFERENCES [SaleInvoice]([Id]), 
    CONSTRAINT [FK_Inventory_Warehouse] FOREIGN KEY ([Warehouse_Id]) REFERENCES [Warehouse]([Id]),

)
