CREATE TABLE [dbo].[Campaign_MassEmail]
(
	[Id]								UNIQUEIDENTIFIER NOT NULL , 
    [Total]								DATETIME NULL, 
	[Date]								DATETIME NULL, 
    [Opens]								INT NULL, 
    [Clicks]							INT NULL, 
    [Rebounds]							INT NULL, 
    [Delivers]							INT NULL,
    [Active]							BIT NULL, 
    [Email_Template_Id]					UNIQUEIDENTIFIER NULL, 
    [Campaign_ScheduleEmail_Id]			UNIQUEIDENTIFIER NULL, 
    [Campaign_Id]						UNIQUEIDENTIFIER NULL, 
    [Campaign_Segment_Id]				UNIQUEIDENTIFIER NULL, 
    [RowStatus]							INT					NOT NULL,
	[Locked]							BIT					NOT NULL DEFAULT 0,
	[Required]							BIT					NOT NULL DEFAULT 0,
	[Employee_Id]						UNIQUEIDENTIFIER	NULL,
	[CreatedBy]							UNIQUEIDENTIFIER	NULL,
	[CreatedDate]						DATETIME			NULL,
	[ModifiedBy]						UNIQUEIDENTIFIER	NULL,
	[ModifiedDate]						DATETIME			NULL,
    [Picture] NVARCHAR(MAX) NULL, 
	CONSTRAINT [PK_Campaign_MassEmail] PRIMARY KEY ([Id]), 
    CONSTRAINT [FK_CampaignMassEmail_CampaignScheduleEmail] FOREIGN KEY ([Campaign_ScheduleEmail_Id]) REFERENCES [Campaign_ScheduleEmail]([Id]), 
    CONSTRAINT [FK_CampaignMassEmail_Campaign] FOREIGN KEY ([Campaign_Id]) REFERENCES [Campaign]([Id]), 
    CONSTRAINT [FK_CampaignMassEmail_Segment] FOREIGN KEY ([Campaign_Segment_Id]) REFERENCES [Campaign_Segment]([Id]), 
)
