--CREATE TABLE [dbo].[Employee_Activity]
--(
--	[Id] UNIQUEIDENTIFIER NOT NULL , 
--    [Subject] NVARCHAR(500) NULL, 
--    [DueDate] DATETIME NULL, 
--    [Status] NVARCHAR(300) NULL, 
--    [Priority] NVARCHAR(300) NULL, 
--    [Customer_Id] UNIQUEIDENTIFIER NULL, 
--	[Employee_Id] UNIQUEIDENTIFIER NULL, 
--	[RowStatus]            int                  not null,
--	[Employee_Id]           uniqueidentifier     null,
--	[CreatedBy]            uniqueidentifier     null,
--	[CreatedDate]          datetime             null,
--	[ModifiedBy]           uniqueidentifier     null,
--	[ModifiedDate]         datetime             null, 
--    CONSTRAINT [PK_EmployeeActivity] PRIMARY KEY ([Id]), 
--    CONSTRAINT [FK_EmployeeActivity_Customer] FOREIGN KEY ([Customer_Id]) REFERENCES [Customer]([Id]), 
--    CONSTRAINT [FK_EmployeeActivity_Employee] FOREIGN KEY ([Employee_Id]) REFERENCES [Employee]([Id])
--)
