CREATE TABLE [dbo].[Manufacture]
(
	[Id]								UNIQUEIDENTIFIER	NOT NULL, 
    [BusinessItemVariation_Id]			UNIQUEIDENTIFIER	NOT NULL, 
	[Quantity]							DECIMAL(18, 5)		NOT NULL, 
	[UnitOfMeasure_Id]					UNIQUEIDENTIFIER	NULL,
	[Batch]								BIGINT				NULL,
	[Date]								DATETIME			NULL,
	[StartDate]							DATETIME			NULL,
	[EndDate]							DATETIME			NULL,
	[Warehouse_Id]						UNIQUEIDENTIFIER	NOT NULL,
    [Project_Id]						UNIQUEIDENTIFIER	NOT NULL, 
	[ResponsableEmployee_Id]			UNIQUEIDENTIFIER	NOT NULL,
	[Manufacture_Status_Id]				UNIQUEIDENTIFIER	NOT NULL, 
	[Factory_Id]						UNIQUEIDENTIFIER	NOT NULL, 
	[RowStatus]							INT					NOT NULL,
	[Locked]							BIT					NOT NULL DEFAULT 0,
	[Required]							BIT					NOT NULL DEFAULT 0,
	[Employee_Id]						UNIQUEIDENTIFIER	NULL,
	[CreatedBy]							UNIQUEIDENTIFIER	NULL,
	[CreatedDate]						DATETIME			NULL,
	[ModifiedBy]						UNIQUEIDENTIFIER	NULL,
	[ModifiedDate]						DATETIME			NULL,
    [Picture] NVARCHAR(MAX) NULL, 
    CONSTRAINT [PK_Manufacture] PRIMARY KEY ([Id]),
    CONSTRAINT [FK_Manufacture_ProvisionWarehouse] FOREIGN KEY ([Warehouse_Id]) REFERENCES [Warehouse]([Id]),
    CONSTRAINT [FK_Manufacture_BusinessItemVariation] FOREIGN KEY ([BusinessItemVariation_Id]) REFERENCES [BusinessItemVariation]([Id]),
	CONSTRAINT [FK_Manufacture_UnitOfMeasure] FOREIGN KEY ([UnitOfMeasure_Id]) REFERENCES [UnitOfMeasure]([Id]),
	CONSTRAINT [FK_Manufacture_ProductionCenter] FOREIGN KEY ([Factory_Id]) REFERENCES [Factory]([Id]),
    CONSTRAINT [FK_Manufacture_ManufactureStatus] FOREIGN KEY ([Manufacture_Status_Id]) REFERENCES [Manufacture_Status]([Id]),

)
