CREATE TABLE [dbo].[Customer]
(
	[Id]								UNIQUEIDENTIFIER	NOT NULL, 
	[Parent_Id]							UNIQUEIDENTIFIER	NULL, 
	[LegalIdType_Id]					UNIQUEIDENTIFIER	NULL, 
	[LegalId]							NVARCHAR(50)		NULL, 
	[Photo]							NVARCHAR(MAX)		NULL, 
	[Salutation_Id]						UNIQUEIDENTIFIER	NULL,	--person 
	[Gender_Id]							UNIQUEIDENTIFIER	NULL,	--person 
	[Name1]								NVARCHAR(300)		NULL, 
	[Name2]								NVARCHAR(300)		NULL, 
    [Birth]								DATETIME			NULL, 
	[Email]								NVARCHAR(1000)		NULL,
	[Phone1]							NVARCHAR(1000)		NULL,
	[Phone2]							NVARCHAR(1000)		NULL,
	[Phone3]							NVARCHAR(1000)		NULL,
	[DoNotCall]							BIT					NULL, 
	[DoNotEmail]						BIT					NULL, 
	[DoNotSMS]							BIT					NULL, 
	[LastActivity]						DATETIME			NULL, 
	[Description]						VARCHAR(MAX)		NULL, 
	[Territory_Id]						UNIQUEIDENTIFIER	NULL, 
	[Industry_Id]						UNIQUEIDENTIFIER	NULL,
	[Customer_Type_Id]					UNIQUEIDENTIFIER	NULL, 
    [Customer_RelationshipType_Id]		UNIQUEIDENTIFIER	NULL, 
    [SourceChannel_Id]					UNIQUEIDENTIFIER	NULL, 
    [Campaign_Id]						UNIQUEIDENTIFIER	NULL, 
	[Language_Id]						UNIQUEIDENTIFIER	NULL, 
	[Customer_Rating_Id]				UNIQUEIDENTIFIER	NOT NULL, 
	[Customer_Class_Id]					UNIQUEIDENTIFIER	NOT NULL, 
	[RowStatus]							INT					NOT NULL,
	[Locked]							BIT					NOT NULL DEFAULT 0,
	[Required]							BIT					NOT NULL DEFAULT 0,
	[Employee_Id]						UNIQUEIDENTIFIER	NULL,
	[CreatedBy]							UNIQUEIDENTIFIER	NULL,
	[CreatedDate]						DATETIME			NULL,
	[ModifiedBy]						UNIQUEIDENTIFIER	NULL,
	[ModifiedDate]						DATETIME			NULL,
    [Picture] NVARCHAR(MAX) NULL, 
	CONSTRAINT [FK_Customer_CustomerType] FOREIGN KEY ([Customer_Type_Id]) REFERENCES [Customer_Type]([Id]), 
    CONSTRAINT [PK_Customer] PRIMARY KEY ([Id]), 
    CONSTRAINT [FK_Customer_Customer] FOREIGN KEY ([Parent_Id]) REFERENCES [Customer]([Id]), 
    CONSTRAINT [FK_Customer_Industry] FOREIGN KEY ([Industry_Id]) REFERENCES [Industry]([Id]), 
    CONSTRAINT [FK_Customer_CustomerRelationship] FOREIGN KEY ([Customer_RelationshipType_Id]) REFERENCES [Customer_RelationshipType]([Id]), 
    CONSTRAINT [FK_Customer_SourceChannel] FOREIGN KEY ([SourceChannel_Id]) REFERENCES [SourceChannel]([Id]), 
    CONSTRAINT [FK_Customer_Campaign] FOREIGN KEY ([Campaign_Id]) REFERENCES [Campaign]([Id]), 
    CONSTRAINT [FK_Customer_Language] FOREIGN KEY ([Language_Id]) REFERENCES [Language]([Id]), 
    CONSTRAINT [FK_Customer_Gender] FOREIGN KEY ([Gender_Id]) REFERENCES [Gender]([Id]), 
    CONSTRAINT [FK_Customer_Salutation] FOREIGN KEY ([Salutation_Id]) REFERENCES [Salutation]([Id]), 
    CONSTRAINT [FK_Customer_Employee] FOREIGN KEY ([Employee_Id]) REFERENCES [Employee]([Id]), 
    CONSTRAINT [FK_Customer_Territory] FOREIGN KEY ([Territory_Id]) REFERENCES [Territory]([Id]), 
    CONSTRAINT [FK_Customer_LegalIdType] FOREIGN KEY ([LegalIdType_Id]) REFERENCES [LegalIdType]([Id]),
	CONSTRAINT [FK_Customer_Rating] FOREIGN KEY ([Customer_Rating_Id]) REFERENCES [Customer_Rating]([Id]), 
    CONSTRAINT [FK_Customer_Class] FOREIGN KEY ([Customer_Class_Id]) REFERENCES [Customer_Class]([Id])

)
