CREATE TABLE [dbo].[Account]
(
	[Id]								UNIQUEIDENTIFIER	NOT NULL, 
    --[Class]								NVARCHAR(10)		NOT NULL, 
    --[Group]								NVARCHAR(10)		NULL, 
    --[Account]							NVARCHAR(10)		NULL, 
    --[Subaccount]						NVARCHAR(10)		NULL, 
    --[Helper]							NVARCHAR(10)		NULL, 
    [Code]								NVARCHAR(100)		NOT NULL, 
    [Code2]								NVARCHAR(100)		NULL, 
    [Name]								NVARCHAR(4000)		NOT NULL, 
	[Account_Level4_Id]					UNIQUEIDENTIFIER	NOT NULL,
	[Account_Type_Id]					UNIQUEIDENTIFIER	NOT NULL, 
	[Accounting_FiscalYear_Id]			UNIQUEIDENTIFIER	NOT NULL, 
	[RowStatus]							INT                 NOT NULL,
	[Locked]							BIT					NOT NULL DEFAULT 0,
	[Required]							BIT					NOT NULL DEFAULT 0,
	[Employee_Id]						UNIQUEIDENTIFIER	NULL,
	[CreatedBy]							UNIQUEIDENTIFIER	NULL,
	[CreatedDate]						DATETIME			NULL,
	[ModifiedBy]						UNIQUEIDENTIFIER	NULL,
	[ModifiedDate]						DATETIME			NULL, 
    [Picture] NVARCHAR(MAX) NULL, 
    CONSTRAINT [PK_Account] PRIMARY KEY ([Id]), 
    CONSTRAINT [FK_Account_AccountType] FOREIGN KEY ([Account_Type_Id]) REFERENCES [Account_Type]([Id]), 
    CONSTRAINT [FK_Account_FiscalYear] FOREIGN KEY ([Accounting_FiscalYear_Id]) REFERENCES [Accounting_FiscalYear]([Id]),
    CONSTRAINT [FK_Account_AccountLevel4] FOREIGN KEY ([Account_Level4_Id]) REFERENCES [Account_Level4]([Id]), 

)
