CREATE TABLE [dbo].[Contact_Address]
(
	[Id]								UNIQUEIDENTIFIER	NOT NULL, 
    [Address]							NVARCHAR(500)		NOT NULL, 
    [PostalCode]						NVARCHAR(50)		NULL, 
	[Reference]							NVARCHAR(50)		NULL, 
	[Coordinates]						NVARCHAR(100)		NULL, 
	[City_Id]							UNIQUEIDENTIFIER	NULL, 
	[AddressType_Id]					UNIQUEIDENTIFIER	NULL, 
	[Contact_Id]						UNIQUEIDENTIFIER	NULL, 
	[RowStatus]							INT					NOT NULL,
	[Locked]							BIT					NOT NULL DEFAULT 0,
	[Required]							BIT					NOT NULL DEFAULT 0,
	[Employee_Id]						UNIQUEIDENTIFIER	NULL,
	[CreatedBy]							UNIQUEIDENTIFIER	NULL,
	[CreatedDate]						DATETIME			NULL,
	[ModifiedBy]						UNIQUEIDENTIFIER	NULL,
	[ModifiedDate]						DATETIME			NULL,
    [Picture] NVARCHAR(MAX) NULL, 
    CONSTRAINT [FK_Contact_Address_City] FOREIGN KEY ([City_Id]) REFERENCES [City]([Id]), 
    CONSTRAINT [FK_Contact_Address_AddressType] FOREIGN KEY ([AddressType_Id]) REFERENCES [AddressType]([Id]), 
    CONSTRAINT [FK_Contact_Address_Contact] FOREIGN KEY ([Contact_Id]) REFERENCES [Contact]([Id]), 
    CONSTRAINT [PK_Contact_Address] PRIMARY KEY ([Id]), 
)
