CREATE TABLE [dbo].[Company]
(
	[Id]								UNIQUEIDENTIFIER	NOT NULL, 
    [LegalId]							NVARCHAR(50)		NULL ,
	[Name1]								NVARCHAR(2000)		NOT NULL, 
	[Name2]								NVARCHAR(2000)		NOT NULL, 
	[Address]							NVARCHAR(2000)		NOT NULL, 
	[Phone]								NVARCHAR(200)		NOT NULL, 
    [SignatureName]			            NVARCHAR(500)       NULL, 
    [SignatureKey]		                NVARCHAR(500)       NULL, 
	[AccountingRequired]				NVARCHAR(500)		NOT NULL, 
    [SpecialContributor]                NVARCHAR(500)       NULL, 
    [CurrencyCode]                      NVARCHAR(500)       NULL, 
    [CurrencyName]                      NVARCHAR(500)       NULL, 
	[WebSite]							NVARCHAR(500)		NULL, 
	[Host]								NVARCHAR(300)		NULL, 
	[SmtpHost]							NVARCHAR(500)		NULL, 
	[SmtpPort]							INT					NULL, 
	[SmtpEnableSsl]						BIT					NULL DEFAULT 0, 
    [Image]								NVARCHAR(MAX)		NULL, 
	[MainActivity]						NVARCHAR(MAX)		NOT NULL DEFAULT '', 
	[TaxPayerId]						NVARCHAR(100)		NOT NULL, 
	[Currency_Id]						UNIQUEIDENTIFIER	NOT NULL, 
	[RowStatus]							INT					NOT NULL,
	[Locked]							BIT					NOT NULL DEFAULT 0,
	[Required]							BIT					NOT NULL DEFAULT 0,
	[Employee_Id]						UNIQUEIDENTIFIER	NULL,
	[CreatedBy]							UNIQUEIDENTIFIER	NULL,
	[CreatedDate]						DATETIME			NULL,
	[ModifiedBy]						UNIQUEIDENTIFIER	NULL,
	[ModifiedDate]						DATETIME			NULL,
    [Picture] NVARCHAR(MAX) NULL, 
    CONSTRAINT [PK_Company] PRIMARY KEY ([Id]), 
    CONSTRAINT [FK_Company_Currency] FOREIGN KEY ([Currency_Id]) REFERENCES [Currency]([Id]) 
)
