CREATE TABLE [dbo].[Contact]
(
	[Id]								UNIQUEIDENTIFIER NOT NULL, 
	[LegalId]							NVARCHAR(50)		NULL, 
	[Photo]							NVARCHAR(MAX)		NULL, 
	[Salutation_Id]						UNIQUEIDENTIFIER	NULL,	
	[Gender_Id]							UNIQUEIDENTIFIER	NULL,	
	[FirstName]							NVARCHAR(300)		NULL, 
	[LastName]							NVARCHAR(300)		NULL, 
	[Birth]								DATETIME			NULL, 
	[Email]								NVARCHAR(1000)		NULL,
	[Phone1]							NVARCHAR(1000)		NULL,
	[Phone2]							NVARCHAR(1000)		NULL,
	[Phone3]							NVARCHAR(1000)		NULL,
	[DoNotCall]							BIT					NULL, 
	[DoNotEmail]						BIT					NULL, 
	[DoNotSMS]							BIT					NULL, 
	[LastActivity]						DATETIME			NULL, 
	[Description]						VARCHAR(MAX)		NULL, 
	[Ocupation_Id]						UNIQUEIDENTIFIER	NULL,
    [SourceChannel_Id]					UNIQUEIDENTIFIER	NULL, 
	[Contact_Rating_Id]					UNIQUEIDENTIFIER	NULL, 
	[Language_Id]						UNIQUEIDENTIFIER	NULL, 
	[RowStatus]							INT					NOT NULL,
	[Locked]							BIT					NOT NULL DEFAULT 0,
	[Required]							BIT					NOT NULL DEFAULT 0,
	[Employee_Id]						UNIQUEIDENTIFIER	NULL,
	[CreatedBy]							UNIQUEIDENTIFIER	NULL,
	[CreatedDate]						DATETIME			NULL,
	[ModifiedBy]						UNIQUEIDENTIFIER	NULL,
	[ModifiedDate]						DATETIME			NULL,
    [Picture] NVARCHAR(MAX) NULL, 
    CONSTRAINT [PK_Contact] PRIMARY KEY ([Id]), 
    CONSTRAINT [FK_Contact_Salutation] FOREIGN KEY ([Salutation_Id]) REFERENCES [Salutation]([Id]), 
    CONSTRAINT [FK_Contact_Gender] FOREIGN KEY ([Gender_Id]) REFERENCES [Gender]([Id]), 
    CONSTRAINT [FK_Contact_Ocupation] FOREIGN KEY ([Ocupation_Id]) REFERENCES [Ocupation]([Id]), 
    CONSTRAINT [FK_Contact_Source] FOREIGN KEY ([SourceChannel_Id]) REFERENCES [SourceChannel]([Id]), 
    CONSTRAINT [FK_Contact_Language] FOREIGN KEY ([Language_Id]) REFERENCES [Language]([Id]), 
    CONSTRAINT [FK_Contact_Rating] FOREIGN KEY ([Contact_Rating_Id]) REFERENCES [Contact_Rating]([Id]) 
)
