CREATE TABLE [dbo].[SaleInvoice]
(
	[Id]								UNIQUEIDENTIFIER	NOT NULL, 
	[Batch]								NVARCHAR(100)		NULL,
	[Date]								DATE			NOT NULL, 
	[TotalAmountWithoutTaxes]			DECIMAL(18, 5)		NOT NULL DEFAULT 0, 
	[DiscountAmount]					DECIMAL(18, 5)		NOT NULL DEFAULT 0, 
	[TaxAmount]							DECIMAL(18, 5)		NOT NULL DEFAULT 0, 
	[TipAmount]							DECIMAL(18, 5)		NOT NULL DEFAULT 0, 
	[TotalAmount]						DECIMAL(18, 5)		NOT NULL DEFAULT 0, 
	[CurrencyCode]						NVARCHAR(MAX)		NULL, 
	[CurrencyName]						NVARCHAR(MAX)		NULL, 
	--Customer
	[CustomerName]						NVARCHAR(MAX)		NULL, 
	[CustomerLegalIdTypeCode]			NVARCHAR(MAX)		NULL, 
	[CustomerLegalId]					NVARCHAR(MAX)		NULL, 
	[CustomerBillingAddress]			NVARCHAR(MAX)		NULL,
	[CustomerShippingAddress]			NVARCHAR(MAX)		NULL,
	[CustomerPhone]						NVARCHAR(MAX)		NULL,
	[CustomerEmail]						NVARCHAR(MAX)		NULL,
	--Document
	[Number]							NVARCHAR(MAX)		NULL,
	[DocumentNumber]					AS CONCAT( ISNULL([CompanyPlaceCode],''), '-', ISNULL([CompanyPointOfSaleCode],'') ,'-', ISNULL( [Number], '')),  --Calculado 001-001-000000001
	--Company
	[CompanyLegalId]					NVARCHAR(MAX)		NULL, 
	[CompanyName1]						NVARCHAR(MAX)		NULL, 
	[CompanyName2]						NVARCHAR(MAX)		NULL, 
	[CompanyTaxPayerId]					NVARCHAR(MAX)		NULL, 
	[CompanyAddress]					NVARCHAR(MAX)		NULL, 
	[CompanyPhone]						NVARCHAR(MAX)		NULL, 
	[CompanyAccountingRequired]			NVARCHAR(100)		NULL, 
	--Company_Place
	[CompanyPlaceCode]					NVARCHAR(MAX)		NULL, 
	[CompanyPlaceAddress]				NVARCHAR(MAX)		NULL, 
	[CompanyPlacePhone]					NVARCHAR(MAX)		NULL, 
	[CompanyPointOfSaleCode]			NVARCHAR(MAX)		NULL, 
	--Contract
	[ContractNumber]					BIGINT				NULL, 
	[ContractPhysicalNumber]			NVARCHAR(MAX)		NULL, 
	--Informative fields
	[Informative1]						NVARCHAR(MAX)		NULL, 
	[Informative2]						NVARCHAR(MAX)		NULL, 
	[Informative3]						NVARCHAR(MAX)		NULL, 
	[Informative4]						NVARCHAR(MAX)		NULL, 
	[Informative5]						NVARCHAR(MAX)		NULL, 
	[Informative6]						NVARCHAR(MAX)		NULL, 
	[Informative7]						NVARCHAR(MAX)		NULL, 
	[Informative8]						NVARCHAR(MAX)		NULL, 
	[Informative9]						NVARCHAR(MAX)		NULL, 
	[Informative10]						NVARCHAR(MAX)		NULL, 
	[Informative11]						NVARCHAR(MAX)		NULL, 
	[Informative12]						NVARCHAR(MAX)		NULL, 
	[Informative13]						NVARCHAR(MAX)		NULL, 
	[Informative14]						NVARCHAR(MAX)		NULL, 
	[Informative15]						NVARCHAR(MAX)		NULL, 
	[Sale_Id]							UNIQUEIDENTIFIER	NOT NULL, 
	[SaleInvoice_RecurrentProcess_Id]	UNIQUEIDENTIFIER	NULL,
	[Company_EmissionPoint_Id]			UNIQUEIDENTIFIER	NOT NULL,
	[Xml]								NVARCHAR(MAX)		NULL, 
	[KeyAccess]							NVARCHAR(50)		NULL,
	[VoucherStatus]						NVARCHAR(50)		NULL,
	[VoucherMessages]					NVARCHAR(MAX)		NULL,
	[AuthorizationDate]					DATE				NULL, 
	[RowStatus]							INT					NOT NULL,
	[Locked]							BIT					NOT NULL DEFAULT 0,
	[Required]							BIT					NOT NULL DEFAULT 0,
	[Employee_Id]						UNIQUEIDENTIFIER	NULL,
	[CreatedBy]							UNIQUEIDENTIFIER	NULL,
	[CreatedDate]						DATETIME			NULL,
	[ModifiedBy]						UNIQUEIDENTIFIER	NULL,
	[ModifiedDate]						DATETIME			NULL,
    [Picture] NVARCHAR(MAX) NULL, 
    CONSTRAINT [PK_Invoice] PRIMARY KEY ([Id]), 
    CONSTRAINT [FK_SaleInvoice_Sale] FOREIGN KEY ([Sale_Id]) REFERENCES [Sale]([Id]), 
    CONSTRAINT [FK_SaleInvoice_RecurrentProcess] FOREIGN KEY ([SaleInvoice_RecurrentProcess_Id]) REFERENCES [SaleInvoice_RecurrentProcess]([Id]) ON DELETE CASCADE, 
    CONSTRAINT [FK_SaleInvoice_Company_EmissionPoint] FOREIGN KEY ([Company_EmissionPoint_Id]) REFERENCES [Company_EmissionPoint]([Id]) 
)
